# Copyright (c) 2025 Joan Fabrégat <j@fabreg.at>
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, subject to the conditions in the full MIT License.
# The Software is provided "as is", without warranty of any kind.

services:
  embedding-service:
    container_name: embedding-service
    image: embedding-service:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=80
        - EMBEDDING_MODEL=bert-base-uncased
        - VERSION=v0.0
        - BUILD_ID=XXXXXX
        - COMMIT_SHA=XXXXXX
    ports:
      - "80:80"
