name: vector_db
services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./var/qdrant_storage:/qdrant/storage:delegated

  mysql:
    container_name: mysql
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: &mysqlRootPassword "B3Xj8B0MN0vbNdMRqbG2"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "sophos_vector"
      MYSQL_USER: "sophos_vector"
      MYSQL_PASSWORD: "sophos_vector"
    volumes:
      - ./var/mysql:/var/lib/mysql:delegated
      #- ./mysql.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: *mysqlRootPassword
      UPLOAD_LIMIT: "1G"
      PMA_USER_CONFIG_BASE64: "PD9waHAKJGNmZ1snU2hvd0RhdGFiYXNlc05hdmlnYXRpb25Bc1RyZWUnXSA9IGZhbHNlOwokY2ZnWydOYXZpZ2F0aW9uVHJlZUVuYWJsZUdyb3VwaW5nJ10gPSBmYWxzZTsKJGNmZ1snTWF4TmF2aWdhdGlvbkl0ZW1zJ10gPSAyNTA7CiRjZmdbJ05hdmlnYXRpb25EaXNwbGF5TG9nbyddID0gZmFsc2U7CiRjZmdbJ0xhbmcnXSA9ICdlbic7"
    ports:
      - "81:80"

#  minio:
#    container_name: minio
#    image: minio/minio
#    environment:
#      MINIO_ROOT_USER: "guest"
#      MINIO_ROOT_PASSWORD: "guestguest"
#      MINIO_DEBUG: "on"
#    volumes:
#      - ./var/minio:/data
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    command: server /data --console-address ":9001"

#  rabbitmq:
#    image: rabbitmq:management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - ./var/rabbitmq:/var/lib/rabbitmq
#    restart: always