name: Build and Push Docker Image

on:
  push:
    branches:
      - deploy
    tags:
      - 'v*'

env:
  IMAGE: "joanfabregat/embedding-service"
  ENABLED_MODELS: "bm42,jina_embeddings_v3,e5_large_v2"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      # Build and push Docker image with BuildKit caching
      - name: Build and push Docker image with BuildKit caching
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max
          build-args: |
            APP_VERSION=${{ github.ref_name }}
            ENABLED_MODELS=${{ env.ENABLED_MODELS }}
            APP_BUILD_ID=${{ github.run_id }}
            APP_COMMIT_SHA=${{ github.sha }}